// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8S1nO4QQHUE3ab-XeZuE8rJNV7e6Tm-M',
    appId: '1:586826021959:web:51e28d2f35d913dfc0c562',
    messagingSenderId: '586826021959',
    projectId: 'chatt-app-f9055',
    authDomain: 'chatt-app-f9055.firebaseapp.com',
    storageBucket: 'chatt-app-f9055.appspot.com',
    measurementId: 'G-S29W0118ZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyEkXwCqDal9ZDBfbxF2faTFIzNfyXTMs',
    appId: '1:586826021959:android:b0fc8efff52b41b0c0c562',
    messagingSenderId: '586826021959',
    projectId: 'chatt-app-f9055',
    storageBucket: 'chatt-app-f9055.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbehLyfTyEuTOdqHYPU64HEroYyOJxyxU',
    appId: '1:586826021959:ios:95513cc730e51c98c0c562',
    messagingSenderId: '586826021959',
    projectId: 'chatt-app-f9055',
    storageBucket: 'chatt-app-f9055.appspot.com',
    iosClientId: '586826021959-kopcsh4tt7qg1p7e8rodg758n2aguedr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
